name: LughOS Build and Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache i686-elf toolchain
        id: cache-i686-elf-toolchain
        uses: actions/cache@v4
        with:
          path: i686-elf-tools-linux
          key: ${{ runner.os }}-i686-elf-tools-linux-7.1.0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ binutils nasm gcc-arm-none-eabi binutils-arm-none-eabi
          sudo apt-get install -y gcc-riscv64-linux-gnu binutils-riscv64-linux-gnu
          sudo apt-get install -y cmake make git qemu-system-i386 unzip

      - name: Install i686-elf-gcc
        if: steps.cache-i686-elf-toolchain.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/lordmilko/i686-elf-tools/releases/download/7.1.0/i686-elf-tools-linux.zip
          unzip i686-elf-tools-linux.zip

      - name: Add i686-elf toolchain to PATH
        run: echo "$GITHUB_WORKSPACE/i686-elf-tools-linux/bin" >> $GITHUB_PATH

      - name: Cache NNG build
        id: cache-nng-build
        uses: actions/cache@v4
        with:
          path: nng/build
          key: ${{ runner.os }}-nng-build-v1

      - name: Build and install NNG
        if: steps.cache-nng-build.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/nanomsg/nng.git
          cd nng
          mkdir build && cd build
          cmake -G "Unix Makefiles" ..
          make -j$(nproc)
          sudo make install
          sudo ldconfig

      - name: Build for x86
        run: make x86
        env:
          PATH: ${{ github.workspace }}/i686-elf-tools-linux/bin:${{ env.PATH }}

      - name: Run QEMU x86 tests
        run: ./scripts/test_x86.sh
        env:
          PATH: ${{ github.workspace }}/i686-elf-tools-linux/bin:${{ env.PATH }}

      - name: Build for ARM
        run: make arm
        env:
          PATH: ${{ github.workspace }}/i686-elf-tools-linux/bin:${{ env.PATH }}

      - name: Build for RISC-V
        run: make riscv
        env:
          PATH: ${{ github.workspace }}/i686-elf-tools-linux/bin:${{ env.PATH }}

      - name: Run unit tests
        run: make test
        env:
          PATH: ${{ github.workspace }}/i686-elf-tools-linux/bin:${{ env.PATH }}